import skincareImg1 from "./assets/procedure/skincare/1.png";
import skincareImg2 from "./assets/procedure/skincare/2.png";
import skincareImg3 from "./assets/procedure/skincare/3.png";
import skincareImg4 from "./assets/procedure/skincare/4.png";

import apparatImg1 from "./assets/procedure/apparat/1.png";
import apparatImg2 from "./assets/procedure/apparat/2.png";
import apparatImg3 from "./assets/procedure/apparat/3.png";
import apparatImg4 from "./assets/procedure/apparat/4.png";
import apparatImg5 from "./assets/procedure/apparat/5.png";
import apparatImg6 from "./assets/procedure/apparat/6.png";
import apparatImg7 from "./assets/procedure/apparat/7.png";
import apparatImg8 from "./assets/procedure/apparat/8.png";

import injectImg1 from "./assets/procedure/inject/1.png";
import injectImg2 from "./assets/procedure/inject/2.png";
import injectImg3 from "./assets/procedure/inject/3.png";
import injectImg4 from "./assets/procedure/inject/4.png";
import injectImg5 from "./assets/procedure/inject/5.png";
import injectImg6 from "./assets/procedure/inject/6.png";
import injectImg7 from "./assets/procedure/inject/7.png";
import injectImg8 from "./assets/procedure/inject/8.png";
import injectImg9 from "./assets/procedure/inject/9.png";
import injectImg10 from "./assets/procedure/inject/10.png";
import injectImg11 from "./assets/procedure/inject/11.png";
import injectImg12 from "./assets/procedure/inject/12.png";

const skincare = [
  {
    title: "Чистка лица",
    img: skincareImg1,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Неинвазивная карбокситерапия",
    img: skincareImg2,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Пилинг",
    img: skincareImg3,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Процедуры Maria Galland",
    img: skincareImg4,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
];

const apparat = [
  {
    title: "RF-Лифтинг",
    img: apparatImg1,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Световая терапия",
    img: apparatImg2,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Микродембразия",
    img: apparatImg3,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Дарсонвализация",
    img: apparatImg4,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Прессотерапия",
    img: apparatImg5,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "OXYJET Кислородная терапия",
    img: apparatImg6,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Эндосфера терапия",
    img: apparatImg7,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "HIFU",
    img: apparatImg8,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
];

const inject = [
  {
    title: "Филлеры",
    img: injectImg1,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Ботокс",
    img: injectImg2,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Биоревитализация",
    img: injectImg3,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Биорепарация",
    img: injectImg4,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Мезотерапия",
    img: injectImg5,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Мезонити",
    img: injectImg6,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Дермапен",
    img: injectImg7,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Плазмолифтинг",
    img: injectImg8,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Stamin C",
    img: injectImg9,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Fat Apoptosis",
    img: injectImg10,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Инъкции от целлюлита",
    img: injectImg11,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
  {
    title: "Интимная пластика",
    img: injectImg12,
    description: "",
    shortDescription: "",
    indictions: "",
    contraindications: "",
    time: "",
    price: "",
    number: "",
    frequency: "",
  },
];

export { skincare, apparat, inject };
